//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/10/2014 12:12:10 AM
namespace CarRentalWebClient.CarRentalServiceReference
{
    
    /// <summary>
    /// There are no comments for DbContextModel in the schema.
    /// </summary>
    public partial class DbContextModel : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DbContextModel object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DbContextModel(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "CarRentalWebService.Models", "CarRentalWebClient.CarRentalServiceReference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("CarRentalWebClient.CarRentalServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CarRentalWebService.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for CarBrands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CarBrand> CarBrands
        {
            get
            {
                if ((this._CarBrands == null))
                {
                    this._CarBrands = base.CreateQuery<CarBrand>("CarBrands");
                }
                return this._CarBrands;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CarBrand> _CarBrands;
        /// <summary>
        /// There are no comments for CarModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CarModel> CarModels
        {
            get
            {
                if ((this._CarModels == null))
                {
                    this._CarModels = base.CreateQuery<CarModel>("CarModels");
                }
                return this._CarModels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CarModel> _CarModels;
        /// <summary>
        /// There are no comments for CarFeatures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CarFeature> CarFeatures
        {
            get
            {
                if ((this._CarFeatures == null))
                {
                    this._CarFeatures = base.CreateQuery<CarFeature>("CarFeatures");
                }
                return this._CarFeatures;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CarFeature> _CarFeatures;
        /// <summary>
        /// There are no comments for Requests in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Request> Requests
        {
            get
            {
                if ((this._Requests == null))
                {
                    this._Requests = base.CreateQuery<Request>("Requests");
                }
                return this._Requests;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Request> _Requests;
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<City> Cities
        {
            get
            {
                if ((this._Cities == null))
                {
                    this._Cities = base.CreateQuery<City>("Cities");
                }
                return this._Cities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<City> _Cities;
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Review> Reviews
        {
            get
            {
                if ((this._Reviews == null))
                {
                    this._Reviews = base.CreateQuery<Review>("Reviews");
                }
                return this._Reviews;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Review> _Reviews;
        /// <summary>
        /// There are no comments for CarBrands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCarBrands(CarBrand carBrand)
        {
            base.AddObject("CarBrands", carBrand);
        }
        /// <summary>
        /// There are no comments for CarModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCarModels(CarModel carModel)
        {
            base.AddObject("CarModels", carModel);
        }
        /// <summary>
        /// There are no comments for CarFeatures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCarFeatures(CarFeature carFeature)
        {
            base.AddObject("CarFeatures", carFeature);
        }
        /// <summary>
        /// There are no comments for Requests in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRequests(Request request)
        {
            base.AddObject("Requests", request);
        }
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCities(City city)
        {
            base.AddObject("Cities", city);
        }
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"CarRentalWebService.Models\" xmlns=\"http://schemas.microsoft.com/ado/2" +
                "009/11/edm\"><EntityType Name=\"CarBrand\"><Key><PropertyRef Name=\"Id\" /></Key><Pro" +
                "perty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Iden" +
                "tity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Prop" +
                "erty Name=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"" +
                "true\" /><NavigationProperty Name=\"CarModels\" Relationship=\"CarRentalWebService.M" +
                "odels.CarModel_Brand\" ToRole=\"CarModel_Brand_Source\" FromRole=\"CarModel_Brand_Ta" +
                "rget\" /></EntityType><EntityType Name=\"CarModel\"><Key><PropertyRef Name=\"Id\" /><" +
                "/Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPatt" +
                "ern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation" +
                "\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" " +
                "Unicode=\"true\" /><Property Name=\"Image\" Type=\"Edm.String\" MaxLength=\"Max\" FixedL" +
                "ength=\"false\" Unicode=\"true\" /><Property Name=\"AutoTransmission\" Type=\"Edm.Boole" +
                "an\" Nullable=\"false\" /><Property Name=\"Aircondition\" Type=\"Edm.Boolean\" Nullable" +
                "=\"false\" /><Property Name=\"Seats\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property " +
                "Name=\"Doors\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"LargeBags\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"SmallBags\" Type=\"Edm.Int32\" Null" +
                "able=\"false\" /><Property Name=\"PricePerDay\" Type=\"Edm.Int32\" Nullable=\"false\" />" +
                "<Property Name=\"PricePerHour\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"Quantity\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Brand_Id\" Type=\"" +
                "Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Brand\" Relationship=\"Car" +
                "RentalWebService.Models.CarModel_Brand\" ToRole=\"CarModel_Brand_Target\" FromRole=" +
                "\"CarModel_Brand_Source\" /><NavigationProperty Name=\"Features\" Relationship=\"CarR" +
                "entalWebService.Models.CarFeature_CarModels\" ToRole=\"CarFeature_CarModels_Source" +
                "\" FromRole=\"CarFeature_CarModels_Target\" /><NavigationProperty Name=\"Requests\" R" +
                "elationship=\"CarRentalWebService.Models.Request_Model\" ToRole=\"Request_Model_Sou" +
                "rce\" FromRole=\"Request_Model_Target\" /><NavigationProperty Name=\"Reviews\" Relati" +
                "onship=\"CarRentalWebService.Models.Review_Model\" ToRole=\"Review_Model_Source\" Fr" +
                "omRole=\"Review_Model_Target\" /></EntityType><EntityType Name=\"CarFeature\"><Key><" +
                "PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/a" +
                "do/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLength=\"" +
                "Max\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"CarModels\" R" +
                "elationship=\"CarRentalWebService.Models.CarFeature_CarModels\" ToRole=\"CarFeature" +
                "_CarModels_Target\" FromRole=\"CarFeature_CarModels_Source\" /></EntityType><Entity" +
                "Type Name=\"Request\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http" +
                "://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Typ" +
                "e=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Na" +
                "me=\"Email\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"Phone\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" U" +
                "nicode=\"true\" /><Property Name=\"FromDate\" Type=\"Edm.DateTime\" /><Property Name=\"" +
                "ToDate\" Type=\"Edm.DateTime\" /><Property Name=\"PriceTotal\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" /><Property Name=\"State\" Type=\"Edm.Int32\" Nullable=\"false\" /><Proper" +
                "ty Name=\"Model_Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"City_Id\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"City\" Relationship" +
                "=\"CarRentalWebService.Models.Request_City\" ToRole=\"Request_City_Target\" FromRole" +
                "=\"Request_City_Source\" /><NavigationProperty Name=\"Model\" Relationship=\"CarRenta" +
                "lWebService.Models.Request_Model\" ToRole=\"Request_Model_Target\" FromRole=\"Reques" +
                "t_Model_Source\" /></EntityType><EntityType Name=\"City\"><Key><PropertyRef Name=\"I" +
                "d\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGenerat" +
                "edPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/anno" +
                "tation\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"f" +
                "alse\" Unicode=\"true\" /><Property Name=\"ZipCode\" Type=\"Edm.Int32\" Nullable=\"false" +
                "\" /><NavigationProperty Name=\"Requests\" Relationship=\"CarRentalWebService.Models" +
                ".Request_City\" ToRole=\"Request_City_Source\" FromRole=\"Request_City_Target\" /></E" +
                "ntityType><EntityType Name=\"Review\"><Key><PropertyRef Name=\"Id\" /></Key><Propert" +
                "y Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity" +
                "\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property" +
                " Name=\"Model_Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Content\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property N" +
                "ame=\"Stars\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"email\" Type=\"Edm" +
                ".String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><NavigationPropert" +
                "y Name=\"Model\" Relationship=\"CarRentalWebService.Models.Review_Model\" ToRole=\"Re" +
                "view_Model_Target\" FromRole=\"Review_Model_Source\" /></EntityType><Association Na" +
                "me=\"CarModel_Brand\"><End Type=\"CarRentalWebService.Models.CarBrand\" Role=\"CarMod" +
                "el_Brand_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"" +
                "CarRentalWebService.Models.CarModel\" Role=\"CarModel_Brand_Source\" Multiplicity=\"" +
                "*\" /><ReferentialConstraint><Principal Role=\"CarModel_Brand_Target\"><PropertyRef" +
                " Name=\"Id\" /></Principal><Dependent Role=\"CarModel_Brand_Source\"><PropertyRef Na" +
                "me=\"Brand_Id\" /></Dependent></ReferentialConstraint></Association><Association N" +
                "ame=\"CarFeature_CarModels\"><End Type=\"CarRentalWebService.Models.CarFeature\" Rol" +
                "e=\"CarFeature_CarModels_Source\" Multiplicity=\"*\" /><End Type=\"CarRentalWebServic" +
                "e.Models.CarModel\" Role=\"CarFeature_CarModels_Target\" Multiplicity=\"*\" /></Assoc" +
                "iation><Association Name=\"Request_Model\"><End Type=\"CarRentalWebService.Models.C" +
                "arModel\" Role=\"Request_Model_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\"" +
                " /></End><End Type=\"CarRentalWebService.Models.Request\" Role=\"Request_Model_Sour" +
                "ce\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Request_Model_Tar" +
                "get\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Request_Model_Source\"" +
                "><PropertyRef Name=\"Model_Id\" /></Dependent></ReferentialConstraint></Associatio" +
                "n><Association Name=\"Review_Model\"><End Type=\"CarRentalWebService.Models.CarMode" +
                "l\" Role=\"Review_Model_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></En" +
                "d><End Type=\"CarRentalWebService.Models.Review\" Role=\"Review_Model_Source\" Multi" +
                "plicity=\"*\" /><ReferentialConstraint><Principal Role=\"Review_Model_Target\"><Prop" +
                "ertyRef Name=\"Id\" /></Principal><Dependent Role=\"Review_Model_Source\"><PropertyR" +
                "ef Name=\"Model_Id\" /></Dependent></ReferentialConstraint></Association><Associat" +
                "ion Name=\"Request_City\"><End Type=\"CarRentalWebService.Models.City\" Role=\"Reques" +
                "t_City_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"Ca" +
                "rRentalWebService.Models.Request\" Role=\"Request_City_Source\" Multiplicity=\"*\" />" +
                "<ReferentialConstraint><Principal Role=\"Request_City_Target\"><PropertyRef Name=\"" +
                "Id\" /></Principal><Dependent Role=\"Request_City_Source\"><Pr";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "opertyRef Name=\"City_Id\" /></Dependent></ReferentialConstraint></Association><Ent" +
                "ityContainer Name=\"DbContextModel\" m:IsDefaultEntityContainer=\"true\"><EntitySet " +
                "Name=\"CarBrands\" EntityType=\"CarRentalWebService.Models.CarBrand\" /><EntitySet N" +
                "ame=\"CarModels\" EntityType=\"CarRentalWebService.Models.CarModel\" /><EntitySet Na" +
                "me=\"CarFeatures\" EntityType=\"CarRentalWebService.Models.CarFeature\" /><EntitySet" +
                " Name=\"Requests\" EntityType=\"CarRentalWebService.Models.Request\" /><EntitySet Na" +
                "me=\"Cities\" EntityType=\"CarRentalWebService.Models.City\" /><EntitySet Name=\"Revi" +
                "ews\" EntityType=\"CarRentalWebService.Models.Review\" /><AssociationSet Name=\"CarM" +
                "odel_Brand\" Association=\"CarRentalWebService.Models.CarModel_Brand\"><End Role=\"C" +
                "arModel_Brand_Target\" EntitySet=\"CarBrands\" /><End Role=\"CarModel_Brand_Source\" " +
                "EntitySet=\"CarModels\" /></AssociationSet><AssociationSet Name=\"CarFeature_CarMod" +
                "els\" Association=\"CarRentalWebService.Models.CarFeature_CarModels\"><End Role=\"Ca" +
                "rFeature_CarModels_Target\" EntitySet=\"CarModels\" /><End Role=\"CarFeature_CarMode" +
                "ls_Source\" EntitySet=\"CarFeatures\" /></AssociationSet><AssociationSet Name=\"Requ" +
                "est_Model\" Association=\"CarRentalWebService.Models.Request_Model\"><End Role=\"Req" +
                "uest_Model_Target\" EntitySet=\"CarModels\" /><End Role=\"Request_Model_Source\" Enti" +
                "tySet=\"Requests\" /></AssociationSet><AssociationSet Name=\"Review_Model\" Associat" +
                "ion=\"CarRentalWebService.Models.Review_Model\"><End Role=\"Review_Model_Target\" En" +
                "titySet=\"CarModels\" /><End Role=\"Review_Model_Source\" EntitySet=\"Reviews\" /></As" +
                "sociationSet><AssociationSet Name=\"Request_City\" Association=\"CarRentalWebServic" +
                "e.Models.Request_City\"><End Role=\"Request_City_Source\" EntitySet=\"Requests\" /><E" +
                "nd Role=\"Request_City_Target\" EntitySet=\"Cities\" /></AssociationSet></EntityCont" +
                "ainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for CarRentalWebService.Models.CarBrand in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class CarBrand
    {
        /// <summary>
        /// Create a new CarBrand object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CarBrand CreateCarBrand(int ID)
        {
            CarBrand carBrand = new CarBrand();
            carBrand.Id = ID;
            return carBrand;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for CarModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<CarModel> CarModels
        {
            get
            {
                return this._CarModels;
            }
            set
            {
                if ((value != null))
                {
                    this._CarModels = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<CarModel> _CarModels = new global::System.Collections.ObjectModel.Collection<CarModel>();
    }
    /// <summary>
    /// There are no comments for CarRentalWebService.Models.CarModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class CarModel
    {
        /// <summary>
        /// Create a new CarModel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="autoTransmission">Initial value of AutoTransmission.</param>
        /// <param name="aircondition">Initial value of Aircondition.</param>
        /// <param name="seats">Initial value of Seats.</param>
        /// <param name="doors">Initial value of Doors.</param>
        /// <param name="largeBags">Initial value of LargeBags.</param>
        /// <param name="smallBags">Initial value of SmallBags.</param>
        /// <param name="pricePerDay">Initial value of PricePerDay.</param>
        /// <param name="pricePerHour">Initial value of PricePerHour.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="brand_Id">Initial value of Brand_Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CarModel CreateCarModel(int ID, bool autoTransmission, bool aircondition, int seats, int doors, int largeBags, int smallBags, int pricePerDay, int pricePerHour, int quantity, int brand_Id)
        {
            CarModel carModel = new CarModel();
            carModel.Id = ID;
            carModel.AutoTransmission = autoTransmission;
            carModel.Aircondition = aircondition;
            carModel.Seats = seats;
            carModel.Doors = doors;
            carModel.LargeBags = largeBags;
            carModel.SmallBags = smallBags;
            carModel.PricePerDay = pricePerDay;
            carModel.PricePerHour = pricePerHour;
            carModel.Quantity = quantity;
            carModel.Brand_Id = brand_Id;
            return carModel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property AutoTransmission in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool AutoTransmission
        {
            get
            {
                return this._AutoTransmission;
            }
            set
            {
                this.OnAutoTransmissionChanging(value);
                this._AutoTransmission = value;
                this.OnAutoTransmissionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _AutoTransmission;
        partial void OnAutoTransmissionChanging(bool value);
        partial void OnAutoTransmissionChanged();
        /// <summary>
        /// There are no comments for Property Aircondition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Aircondition
        {
            get
            {
                return this._Aircondition;
            }
            set
            {
                this.OnAirconditionChanging(value);
                this._Aircondition = value;
                this.OnAirconditionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Aircondition;
        partial void OnAirconditionChanging(bool value);
        partial void OnAirconditionChanged();
        /// <summary>
        /// There are no comments for Property Seats in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Seats
        {
            get
            {
                return this._Seats;
            }
            set
            {
                this.OnSeatsChanging(value);
                this._Seats = value;
                this.OnSeatsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Seats;
        partial void OnSeatsChanging(int value);
        partial void OnSeatsChanged();
        /// <summary>
        /// There are no comments for Property Doors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Doors
        {
            get
            {
                return this._Doors;
            }
            set
            {
                this.OnDoorsChanging(value);
                this._Doors = value;
                this.OnDoorsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Doors;
        partial void OnDoorsChanging(int value);
        partial void OnDoorsChanged();
        /// <summary>
        /// There are no comments for Property LargeBags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LargeBags
        {
            get
            {
                return this._LargeBags;
            }
            set
            {
                this.OnLargeBagsChanging(value);
                this._LargeBags = value;
                this.OnLargeBagsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LargeBags;
        partial void OnLargeBagsChanging(int value);
        partial void OnLargeBagsChanged();
        /// <summary>
        /// There are no comments for Property SmallBags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SmallBags
        {
            get
            {
                return this._SmallBags;
            }
            set
            {
                this.OnSmallBagsChanging(value);
                this._SmallBags = value;
                this.OnSmallBagsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SmallBags;
        partial void OnSmallBagsChanging(int value);
        partial void OnSmallBagsChanged();
        /// <summary>
        /// There are no comments for Property PricePerDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PricePerDay
        {
            get
            {
                return this._PricePerDay;
            }
            set
            {
                this.OnPricePerDayChanging(value);
                this._PricePerDay = value;
                this.OnPricePerDayChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PricePerDay;
        partial void OnPricePerDayChanging(int value);
        partial void OnPricePerDayChanged();
        /// <summary>
        /// There are no comments for Property PricePerHour in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PricePerHour
        {
            get
            {
                return this._PricePerHour;
            }
            set
            {
                this.OnPricePerHourChanging(value);
                this._PricePerHour = value;
                this.OnPricePerHourChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PricePerHour;
        partial void OnPricePerHourChanging(int value);
        partial void OnPricePerHourChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Brand_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Brand_Id
        {
            get
            {
                return this._Brand_Id;
            }
            set
            {
                this.OnBrand_IdChanging(value);
                this._Brand_Id = value;
                this.OnBrand_IdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Brand_Id;
        partial void OnBrand_IdChanging(int value);
        partial void OnBrand_IdChanged();
        /// <summary>
        /// There are no comments for Brand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CarBrand Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                this._Brand = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CarBrand _Brand;
        /// <summary>
        /// There are no comments for Features in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<CarFeature> Features
        {
            get
            {
                return this._Features;
            }
            set
            {
                if ((value != null))
                {
                    this._Features = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<CarFeature> _Features = new global::System.Collections.ObjectModel.Collection<CarFeature>();
        /// <summary>
        /// There are no comments for Requests in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Request> Requests
        {
            get
            {
                return this._Requests;
            }
            set
            {
                if ((value != null))
                {
                    this._Requests = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Request> _Requests = new global::System.Collections.ObjectModel.Collection<Request>();
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Review> Reviews
        {
            get
            {
                return this._Reviews;
            }
            set
            {
                if ((value != null))
                {
                    this._Reviews = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Review> _Reviews = new global::System.Collections.ObjectModel.Collection<Review>();
    }
    /// <summary>
    /// There are no comments for CarRentalWebService.Models.CarFeature in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class CarFeature
    {
        /// <summary>
        /// Create a new CarFeature object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CarFeature CreateCarFeature(int ID)
        {
            CarFeature carFeature = new CarFeature();
            carFeature.Id = ID;
            return carFeature;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for CarModels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<CarModel> CarModels
        {
            get
            {
                return this._CarModels;
            }
            set
            {
                if ((value != null))
                {
                    this._CarModels = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<CarModel> _CarModels = new global::System.Collections.ObjectModel.Collection<CarModel>();
    }
    /// <summary>
    /// There are no comments for CarRentalWebService.Models.Request in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Request
    {
        /// <summary>
        /// Create a new Request object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="priceTotal">Initial value of PriceTotal.</param>
        /// <param name="state">Initial value of State.</param>
        /// <param name="model_Id">Initial value of Model_Id.</param>
        /// <param name="city_Id">Initial value of City_Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Request CreateRequest(int ID, int priceTotal, int state, int model_Id, int city_Id)
        {
            Request request = new Request();
            request.Id = ID;
            request.PriceTotal = priceTotal;
            request.State = state;
            request.Model_Id = model_Id;
            request.City_Id = city_Id;
            return request;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property FromDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> FromDate
        {
            get
            {
                return this._FromDate;
            }
            set
            {
                this.OnFromDateChanging(value);
                this._FromDate = value;
                this.OnFromDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _FromDate;
        partial void OnFromDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnFromDateChanged();
        /// <summary>
        /// There are no comments for Property ToDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ToDate
        {
            get
            {
                return this._ToDate;
            }
            set
            {
                this.OnToDateChanging(value);
                this._ToDate = value;
                this.OnToDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ToDate;
        partial void OnToDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnToDateChanged();
        /// <summary>
        /// There are no comments for Property PriceTotal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PriceTotal
        {
            get
            {
                return this._PriceTotal;
            }
            set
            {
                this.OnPriceTotalChanging(value);
                this._PriceTotal = value;
                this.OnPriceTotalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PriceTotal;
        partial void OnPriceTotalChanging(int value);
        partial void OnPriceTotalChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _State;
        partial void OnStateChanging(int value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property Model_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Model_Id
        {
            get
            {
                return this._Model_Id;
            }
            set
            {
                this.OnModel_IdChanging(value);
                this._Model_Id = value;
                this.OnModel_IdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Model_Id;
        partial void OnModel_IdChanging(int value);
        partial void OnModel_IdChanged();
        /// <summary>
        /// There are no comments for Property City_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int City_Id
        {
            get
            {
                return this._City_Id;
            }
            set
            {
                this.OnCity_IdChanging(value);
                this._City_Id = value;
                this.OnCity_IdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _City_Id;
        partial void OnCity_IdChanging(int value);
        partial void OnCity_IdChanged();
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public City City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private City _City;
        /// <summary>
        /// There are no comments for Model in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CarModel Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this._Model = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CarModel _Model;
    }
    /// <summary>
    /// There are no comments for CarRentalWebService.Models.City in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class City
    {
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="zipCode">Initial value of ZipCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static City CreateCity(int ID, int zipCode)
        {
            City city = new City();
            city.Id = ID;
            city.ZipCode = zipCode;
            return city;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ZipCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ZipCode
        {
            get
            {
                return this._ZipCode;
            }
            set
            {
                this.OnZipCodeChanging(value);
                this._ZipCode = value;
                this.OnZipCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ZipCode;
        partial void OnZipCodeChanging(int value);
        partial void OnZipCodeChanged();
        /// <summary>
        /// There are no comments for Requests in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Request> Requests
        {
            get
            {
                return this._Requests;
            }
            set
            {
                if ((value != null))
                {
                    this._Requests = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Request> _Requests = new global::System.Collections.ObjectModel.Collection<Request>();
    }
    /// <summary>
    /// There are no comments for CarRentalWebService.Models.Review in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Review
    {
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="model_Id">Initial value of Model_Id.</param>
        /// <param name="stars">Initial value of Stars.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Review CreateReview(int ID, int model_Id, int stars)
        {
            Review review = new Review();
            review.Id = ID;
            review.Model_Id = model_Id;
            review.Stars = stars;
            return review;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Model_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Model_Id
        {
            get
            {
                return this._Model_Id;
            }
            set
            {
                this.OnModel_IdChanging(value);
                this._Model_Id = value;
                this.OnModel_IdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Model_Id;
        partial void OnModel_IdChanging(int value);
        partial void OnModel_IdChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this._Content = value;
                this.OnContentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Stars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Stars
        {
            get
            {
                return this._Stars;
            }
            set
            {
                this.OnStarsChanging(value);
                this._Stars = value;
                this.OnStarsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Stars;
        partial void OnStarsChanging(int value);
        partial void OnStarsChanged();
        /// <summary>
        /// There are no comments for Property email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this._email = value;
                this.OnemailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// There are no comments for Model in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CarModel Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this._Model = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CarModel _Model;
    }
}
